# -*- coding: utf-8 -*-
"""movie-catalogue-using-dictionary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KHX9M4wvfbF_3Zv6lhtyDeVutlT3SQVn

"""

# To display menu
def display_menu():
    print('----------\n MENU \n----------')
    print('1 - View all movies')
    print('2 - Add a movie')
    print('3 - Remove a movie')
    print('4 - Exit all')
    print()

#To view all movies
def view(movie_list):
    header = '----------\n Movie list \n----------'
    print(header)

    if len(movie_list) == 0:
        print('There are no movies in the list. \n')
    else:
        i = 1
    for row in movie_list:
        print(
        str(i) + ". " + row["Name"] + " | " + str(row["Year"]) +
        " | Directed by: " + row["Director"] + " | Rating: " +
        str(row["Rating"]))
        i += 1
    print()


#To add new movie
def add(movie_list):
    name = input("Name of Movie: ")
    year = int(input("Year of movie: "))
    director = input("Name of Director: ")
    rating = int(input("Rating for movie (out of 10): "))
    movie_dict = {}
    movie_dict["Name"] = name
    movie_dict["Year"] = year
    movie_dict["Director"] = director
    movie_dict["Rating"] = rating
    movie_list.append(movie_dict)
    print(movie_dict["Name"] + " was added.\n")

#To remove movie
def remove(movie_list):
    number = int(input("Kindly select number of movie to remove: "))
    
    if number < 1 or number > len(movie_list):
        print("Movie number entered is invalid. \n")
    else:
        movie_dict = movie_list.pop(number - 1)
        print(movie_dict["Name"] + " was removed successfully. \n")

#make lists of movies by using dictionary
def main():
    movie_list = [{
    "Name": 'How the Grinch Stole Christmas',
    "Year": 2010,
    "Director": 'Ron Howard',
    "Rating": 6.2
  }, {
    "Name": 'Rogue one',
    "Year": 2016,
    "Director": 'Gareth Edwards',
    "Rating": 7.8
  }, {
    "Name": "The Martian",
    "Year": 2015,
    "Director": 'Ridley Scott',
    "Rating": 7.4
  }, {
    "Name": "Downton Abbey",
    "Year": 2022,
    "Director": 'Robert Schwentke',
    "Rating": 5.7
  }, {
    "Name": "A New Era",
    "Year": 2016,
    "Director": 'Simon Curtis',
    "Rating": 6.1
  }]

    display_menu()
    while True:
        command = input("Please enter your option here: ")
        
        if command == "1":
            view(movie_list)

        elif command == "2":
            add(movie_list)

        elif command == "3":
            remove(movie_list)

        elif command == "4":
            return

        else:
            print("Command you entered is invalid. Please try again. \n")


if __name__ == "__main__":
    main()
